### ISSUE TITLE
Walking back from buildings

### ISSUE THREAD

**Issue by moderncocoafarmer** [moderncocoafarmer/MCF#32]
Not falling into well or the sound

**Comment by AlanWills** [comment]
Have child moving back a little before the timer ends so that it syncs correctly.

**Comment by AlanWills** [comment]
This is done, but I've had to make some changes to accommodate it:

1)  Children do not pause walking when game paused - I don't think this is too bad as other parts of the game do not stop either (e.g. walking animation in top UI)

2)  Could not get children walking back slightly earlier.  It's just too difficult with events like 'black pod' and if there are inconsistencies, i.e. a child going and coming back, we can look at this again.

3)  I've had to change the Plague of black pod so that rather than the child staying another month, they have to go back for another month.  Again, I don't think this really changes the event & it makes the programming a lot easier.
